package com.softisland.api.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVideos<M extends BaseVideos<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setVideoId(java.lang.Integer videoId) {
		set("video_id", videoId);
		return (M)this;
	}
	
	public java.lang.Integer getVideoId() {
		return getInt("video_id");
	}

	public M setVideoName(java.lang.String videoName) {
		set("video_name", videoName);
		return (M)this;
	}
	
	public java.lang.String getVideoName() {
		return getStr("video_name");
	}

	public M setThumbImg(java.lang.String thumbImg) {
		set("thumb_img", thumbImg);
		return (M)this;
	}
	
	public java.lang.String getThumbImg() {
		return getStr("thumb_img");
	}

	public M setDetailUrl(java.lang.String detailUrl) {
		set("detail_url", detailUrl);
		return (M)this;
	}
	
	public java.lang.String getDetailUrl() {
		return getStr("detail_url");
	}

	public M setPlayerThumbImg(java.lang.String playerThumbImg) {
		set("player_thumb_img", playerThumbImg);
		return (M)this;
	}
	
	public java.lang.String getPlayerThumbImg() {
		return getStr("player_thumb_img");
	}

	public M setVideoType(java.lang.String videoType) {
		set("video_type", videoType);
		return (M)this;
	}
	
	public java.lang.String getVideoType() {
		return getStr("video_type");
	}

	public M setVideoUrl(java.lang.String videoUrl) {
		set("video_url", videoUrl);
		return (M)this;
	}
	
	public java.lang.String getVideoUrl() {
		return getStr("video_url");
	}

	public M setPlayerHtml(java.lang.String playerHtml) {
		set("player_html", playerHtml);
		return (M)this;
	}
	
	public java.lang.String getPlayerHtml() {
		return getStr("player_html");
	}

}
