package com.softisland.api.common.model;

import com.softisland.api.common.model.base.BaseMostViewed;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MostViewed extends BaseMostViewed<MostViewed> {
	public static final MostViewed dao = new MostViewed().dao();
}
