package com.softisland.api.common.model;

import com.softisland.api.common.model.base.BaseVideos;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Videos extends BaseVideos<Videos> {
	public static final Videos dao = new Videos().dao();
}
